### ISSUE TITLE
Renderer failed to initialize

### ISSUE THREAD

**Issue by OzaKahuu** [ReaperAnon/Middle-Earth-Mod-Loader#3]
The game starts and when i get to the menu screen i press F10 to bring up the menu and it minimizes the tab so i have to click on it in the bar to get it back and the mod menu is open but when i close it thats when i get an error saying something like "Failed to initialize renderer. IDXGISwapChain::ResizeBuffer Failed" and then the game closes out

It also has this on it 0x887A0001

**Comment by ReaperAnon** [comment]
Interesting, have you tried it in windowed, borderless and fullscreen and it's all the same?

**Comment by OzaKahuu** [comment]
The only thing i haven't done is a blood sacrifice

Edit: just realized i had uninstalled Nvidia Experience the day before it started acting up so im gonna see if reinstalling that makes it work

**Comment by OzaKahuu** [comment]
I don't understand why but launching the game through the Geforce Experience makes it cooperate
