### ISSUE TITLE
Flagged as a trojan ("Wacatac")

### ISSUE THREAD

**Issue by ClayfaceGav** [ReaperAnon/Middle-Earth-Mod-Loader#7]
What in this file could make Opera GX & Windows Defender flag it as a trojan? It seems clean but I just want to be safe. Thanks.

**Comment by ReaperAnon** [comment]
Probably because it kinda works like one, that's what antiviruses look for.

**Comment by ClayfaceGav** [comment]
Thanks for the quick response lol. I just wanted an explanation for peace of mind, so thanks for providing that
